# Website metadata
title: "NAPI"
year: "2026"
email: "napi@is.naist.jp"
author: "Brian Godwin Lim"
copyright: ""
description: "NAIST Project for Interns (NAPI)"
baseurl: "/"
url: "https://napi-naist.github.io" # Change to domain
favicon: "/assets/images/favicon.png"
content_width: "920px"
sitemap: false
debug: false

# Color settings
theme_color: "#000000"
brand_color: "#ffffff"
selection:
  color: "#bbb"
  background_color: "#000000"

# Website header
header_transparent: true
header_pages:
  - index.html
  - about.html
  - stories.html
  - apply.html
  - labs.html
  - faq.html

# Banner default settings
banner:
  image: "assets/images/home.jpg"
  opacity: 0.5
  background: "#000000"
  height: "640px"
  min_height: null
  heading_style: "font-weight: bold"
  subheading_style: "font-weight: bold"

# Testimonials settings
permalink: "/stories/:title"
paginate: 5
yat:
  date_format: "%b %d, %Y"

# Code badge setting
code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#ff4e00"
  text_transform: "uppercase"

# Photo previewer settings (PhotoSwipe 5), refer to: https://photoswipe.com/options/
photo_previewer:
  gallery: "section.main"
  children: "a.photo-swipe"
  bgOpacity: 0.8
  padding:
    top: 20
    bottom: 40
    left: 100
    right: 100

# Build settings
highlighter: none
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
